services:
  db:
    image: postgres:16-alpine
    container_name: floussy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: floussy
      POSTGRES_USER: floussy
      POSTGRES_PASSWORD: floussy
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
