"""add_contact_messages

Revision ID: 58f9974613c7
Revises: 20260612_advisor_global_instructions
Create Date: 2026-06-08 14:53:15.912955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58f9974613c7'
down_revision: Union[str, None] = '20260612_advisor_global_instructions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('contact_info', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ticket_ref', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_messages_id'), 'contact_messages', ['id'], unique=False)
    op.create_index(op.f('ix_contact_messages_ticket_ref'), 'contact_messages', ['ticket_ref'], unique=False)
    op.create_table('advisor_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preview_id', sa.String(length=128), nullable=False),
    sa.Column('proposal_id', sa.String(length=128), nullable=False),
    sa.Column('validation_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='accepted', nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_hash_at_accept', sa.String(length=128), nullable=False),
    sa.Column('engine_version_at_accept', sa.String(length=64), nullable=False),
    sa.Column('apply_ready', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consumed_by_apply_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decision_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    op.create_index('ix_advisor_decisions_consumed_by_apply_id', 'advisor_decisions', ['consumed_by_apply_id'], unique=True)
    op.create_index('ix_advisor_decisions_preview_proposal', 'advisor_decisions', ['preview_id', 'proposal_id'], unique=False)
    op.create_index('ix_advisor_decisions_user_status', 'advisor_decisions', ['user_id', 'status'], unique=False)
    op.create_table('advisor_pre_apply_validations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('validation_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('preview_id', sa.String(length=128), nullable=False),
    sa.Column('proposal_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='valid', nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result_ok', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('can_apply', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_profile_hash', sa.String(length=128), nullable=False),
    sa.Column('preview_profile_hash', sa.String(length=128), nullable=False),
    sa.Column('current_engine_version', sa.String(length=64), nullable=False),
    sa.Column('preview_engine_version', sa.String(length=64), nullable=False),
    sa.Column('validation_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('validation_id')
    )
    op.create_index('ix_advisor_validations_expires_at', 'advisor_pre_apply_validations', ['expires_at'], unique=False)
    op.create_index('ix_advisor_validations_idempotence', 'advisor_pre_apply_validations', ['user_id', 'preview_id', 'proposal_id', 'current_profile_hash', 'current_engine_version'], unique=False)
    op.create_index('ix_advisor_validations_user_preview', 'advisor_pre_apply_validations', ['user_id', 'preview_id'], unique=False)
    op.drop_index(op.f('ix_backup_records_created_at'), table_name='backup_records')
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('category_envelope_map', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_distribution_log_items_log_id'), table_name='distribution_log_items')
    op.drop_index(op.f('uq_distribution_log_items_allocation_id_not_null'), table_name='distribution_log_items', postgresql_where='(allocation_id IS NOT NULL)')
    op.drop_index(op.f('ix_distribution_logs_user_created_at'), table_name='distribution_logs')
    op.drop_index(op.f('uq_distribution_logs_income_auto_tx'), table_name='distribution_logs', postgresql_where="(((trigger)::text = 'income_auto'::text) AND (transaction_id IS NOT NULL))")
    op.drop_index(op.f('ix_distribution_rules_user_priority'), table_name='distribution_rules')
    op.drop_index(op.f('ix_distribution_run_items_run_id'), table_name='distribution_run_items')
    op.drop_index(op.f('ix_distribution_runs_user_created'), table_name='distribution_runs')
    op.drop_index(op.f('uq_distribution_runs_tx'), table_name='distribution_runs', postgresql_where='(transaction_id IS NOT NULL)')
    op.drop_index(op.f('ix_distribution_saved_configs_user_signature'), table_name='distribution_saved_configs')
    op.drop_index(op.f('ix_distribution_saved_configs_user_updated'), table_name='distribution_saved_configs')
    op.drop_constraint(op.f('uq_distribution_saved_configs_user_version'), 'distribution_saved_configs', type_='unique')
    op.create_index('uq_distribution_saved_configs_user_version', 'distribution_saved_configs', ['user_id', 'version'], unique=True)
    op.drop_index(op.f('ix_email_campaigns_audience_type'), table_name='email_campaigns')
    op.drop_index(op.f('ix_email_campaigns_created_at'), table_name='email_campaigns')
    op.drop_index(op.f('ix_email_campaigns_deleted_at'), table_name='email_campaigns')
    op.drop_index(op.f('ix_email_campaigns_status'), table_name='email_campaigns')
    op.alter_column('email_deliveries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_email_deliveries_created_at'), table_name='email_deliveries')
    op.alter_column('email_design_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_email_templates_active'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_category'), table_name='email_templates')
    op.drop_index(op.f('ix_email_templates_language'), table_name='email_templates')
    op.alter_column('envelope_allocations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('envelope_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('envelope_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('envelopes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('envelopes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('income_reminders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ip_blocks_created_at'), table_name='ip_blocks')
    op.drop_index(op.f('ix_ip_blocks_ip_address'), table_name='ip_blocks')
    op.alter_column('leaderboard_name_changes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_leaderboard_name_changes_user_month'), table_name='leaderboard_name_changes')
    op.drop_index(op.f('ix_onboarding_v2_records_created_at'), table_name='onboarding_v2_records')
    op.drop_index(op.f('ix_onboarding_v2_records_user_id'), table_name='onboarding_v2_records')
    op.drop_index(op.f('ix_page_views_created_at'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_user_id'), table_name='page_views')
    op.drop_index(op.f('ix_password_reset_tokens_expires'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_created'), table_name='password_reset_tokens')
    op.drop_index(op.f('uq_password_reset_tokens_hash'), table_name='password_reset_tokens')
    op.create_unique_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', ['token_hash'])
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    op.alter_column('points_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_points_log_user_day'), table_name='points_log')
    op.drop_index(op.f('ix_points_log_user_event_day'), table_name='points_log')
    op.drop_index(op.f('ix_superadmin_sessions_last_seen_at'), table_name='superadmin_sessions')
    op.drop_index(op.f('ix_superadmin_sessions_session_token_hash'), table_name='superadmin_sessions')
    op.drop_index(op.f('ix_superadmin_sessions_user_active'), table_name='superadmin_sessions')
    op.alter_column('sweeps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_gamification', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_gamification', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_user_gamification_points_monthly'), table_name='user_gamification')
    op.drop_index(op.f('ix_user_gamification_points_total'), table_name='user_gamification')
    op.drop_index(op.f('ix_user_gamification_points_weekly'), table_name='user_gamification')
    op.alter_column('user_passkeys', 'credential_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_passkeys', 'public_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('user_passkeys', 'aaguid',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_user_shiftpilot_states_user_id'), table_name='user_shiftpilot_states')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_web_login_tokens_token'), table_name='web_login_tokens')
    op.alter_column('webauthn_challenges', 'flow',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webauthn_challenges', 'flow',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_web_login_tokens_token'), 'web_login_tokens', ['token'], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_user_shiftpilot_states_user_id'), 'user_shiftpilot_states', ['user_id'], unique=False)
    op.alter_column('user_passkeys', 'aaguid',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_passkeys', 'public_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_passkeys', 'credential_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_user_gamification_points_weekly'), 'user_gamification', ['points_weekly'], unique=False)
    op.create_index(op.f('ix_user_gamification_points_total'), 'user_gamification', ['points_total'], unique=False)
    op.create_index(op.f('ix_user_gamification_points_monthly'), 'user_gamification', ['points_monthly'], unique=False)
    op.alter_column('user_gamification', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_gamification', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sweeps', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_superadmin_sessions_user_active'), 'superadmin_sessions', ['user_id', 'revoked_at', 'ended_at'], unique=False)
    op.create_index(op.f('ix_superadmin_sessions_session_token_hash'), 'superadmin_sessions', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_superadmin_sessions_last_seen_at'), 'superadmin_sessions', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_points_log_user_event_day'), 'points_log', ['user_id', 'event_type', 'occurred_on'], unique=False)
    op.create_index(op.f('ix_points_log_user_day'), 'points_log', ['user_id', 'occurred_on'], unique=False)
    op.alter_column('points_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.drop_constraint('password_reset_tokens_token_hash_key', 'password_reset_tokens', type_='unique')
    op.create_index(op.f('uq_password_reset_tokens_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_created'), 'password_reset_tokens', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_expires'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_page_views_user_id'), 'page_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_page_views_created_at'), 'page_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_onboarding_v2_records_user_id'), 'onboarding_v2_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_onboarding_v2_records_created_at'), 'onboarding_v2_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_leaderboard_name_changes_user_month'), 'leaderboard_name_changes', ['user_id', 'changed_on'], unique=False)
    op.alter_column('leaderboard_name_changes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ip_blocks_ip_address'), 'ip_blocks', ['ip_address'], unique=True)
    op.create_index(op.f('ix_ip_blocks_created_at'), 'ip_blocks', ['created_at'], unique=False)
    op.alter_column('income_reminders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('envelopes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('envelopes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('envelope_periods', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('envelope_movements', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('envelope_allocations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_email_templates_language'), 'email_templates', ['language'], unique=False)
    op.create_index(op.f('ix_email_templates_category'), 'email_templates', ['category'], unique=False)
    op.create_index(op.f('ix_email_templates_active'), 'email_templates', ['is_active'], unique=False)
    op.alter_column('email_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_design_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_email_deliveries_created_at'), 'email_deliveries', ['created_at'], unique=False)
    op.alter_column('email_deliveries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_email_campaigns_status'), 'email_campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_email_campaigns_deleted_at'), 'email_campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_email_campaigns_created_at'), 'email_campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_campaigns_audience_type'), 'email_campaigns', ['audience_type'], unique=False)
    op.drop_index('uq_distribution_saved_configs_user_version', table_name='distribution_saved_configs')
    op.create_unique_constraint(op.f('uq_distribution_saved_configs_user_version'), 'distribution_saved_configs', ['user_id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_distribution_saved_configs_user_updated'), 'distribution_saved_configs', ['user_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_distribution_saved_configs_user_signature'), 'distribution_saved_configs', ['user_id', 'signature'], unique=False)
    op.create_index(op.f('uq_distribution_runs_tx'), 'distribution_runs', ['user_id', 'transaction_id'], unique=True, postgresql_where='(transaction_id IS NOT NULL)')
    op.create_index(op.f('ix_distribution_runs_user_created'), 'distribution_runs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_distribution_run_items_run_id'), 'distribution_run_items', ['run_id'], unique=False)
    op.create_index(op.f('ix_distribution_rules_user_priority'), 'distribution_rules', ['user_id', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('uq_distribution_logs_income_auto_tx'), 'distribution_logs', ['user_id', 'transaction_id'], unique=True, postgresql_where="(((trigger)::text = 'income_auto'::text) AND (transaction_id IS NOT NULL))")
    op.create_index(op.f('ix_distribution_logs_user_created_at'), 'distribution_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('uq_distribution_log_items_allocation_id_not_null'), 'distribution_log_items', ['allocation_id'], unique=True, postgresql_where='(allocation_id IS NOT NULL)')
    op.create_index(op.f('ix_distribution_log_items_log_id'), 'distribution_log_items', ['log_id'], unique=False)
    op.alter_column('category_envelope_map', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_backup_records_created_at'), 'backup_records', ['created_at'], unique=False)
    op.drop_index('ix_advisor_validations_user_preview', table_name='advisor_pre_apply_validations')
    op.drop_index('ix_advisor_validations_idempotence', table_name='advisor_pre_apply_validations')
    op.drop_index('ix_advisor_validations_expires_at', table_name='advisor_pre_apply_validations')
    op.drop_table('advisor_pre_apply_validations')
    op.drop_index('ix_advisor_decisions_user_status', table_name='advisor_decisions')
    op.drop_index('ix_advisor_decisions_preview_proposal', table_name='advisor_decisions')
    op.drop_index('ix_advisor_decisions_consumed_by_apply_id', table_name='advisor_decisions')
    op.drop_table('advisor_decisions')
    op.drop_index(op.f('ix_contact_messages_ticket_ref'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_id'), table_name='contact_messages')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
