"""add_magic_input_nlp_tables

Revision ID: 9fe616f2d3b7
Revises: 20260626_fix_technical_debt
Create Date: 2026-06-26 13:57:31.952344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe616f2d3b7'
down_revision: Union[str, None] = '20260626_fix_technical_debt'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_category_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=120), nullable=False),
    sa.Column('category_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_category_mappings_keyword'), 'merchant_category_mappings', ['keyword'], unique=True)
    
    # Pre-populate global merchant category mappings
    import uuid
    merchant_category_mappings_table = sa.table(
        'merchant_category_mappings',
        sa.column('id', sa.UUID()),
        sa.column('keyword', sa.String()),
        sa.column('category_name', sa.String())
    )
    op.bulk_insert(merchant_category_mappings_table, [
        {"id": str(uuid.uuid4()), "keyword": "taxi", "category_name": "Transport"},
        {"id": str(uuid.uuid4()), "keyword": "marjane", "category_name": "Alimentation"},
        {"id": str(uuid.uuid4()), "keyword": "bim", "category_name": "Alimentation"},
        {"id": str(uuid.uuid4()), "keyword": "loyer", "category_name": "Loyer"},
        {"id": str(uuid.uuid4()), "keyword": "pharma", "category_name": "Santé"},
        {"id": str(uuid.uuid4()), "keyword": "internet", "category_name": "Abonnements"},
        {"id": str(uuid.uuid4()), "keyword": "carrefour", "category_name": "Alimentation"},
        {"id": str(uuid.uuid4()), "keyword": "uber", "category_name": "Transport"},
        {"id": str(uuid.uuid4()), "keyword": "careem", "category_name": "Transport"},
        {"id": str(uuid.uuid4()), "keyword": "medecin", "category_name": "Santé"}
    ])
    op.create_table('user_category_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('keyword', sa.String(length=120), nullable=False),
    sa.Column('category_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'keyword', name='uq_user_category_preference_user_keyword')
    )
    op.create_index(op.f('ix_user_category_preferences_keyword'), 'user_category_preferences', ['keyword'], unique=False)
    op.create_index(op.f('ix_user_category_preferences_user_id'), 'user_category_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_category_preferences_user_id'), table_name='user_category_preferences')
    op.drop_index(op.f('ix_user_category_preferences_keyword'), table_name='user_category_preferences')
    op.drop_table('user_category_preferences')
    op.drop_index(op.f('ix_merchant_category_mappings_keyword'), table_name='merchant_category_mappings')
    op.drop_table('merchant_category_mappings')
    # ### end Alembic commands ###
