from __future__ import annotations

import asyncio
import os
import sys

ROOT = os.path.dirname(os.path.dirname(__file__))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from sqlalchemy import select
from app.db.session import get_sessionmaker
from app.models.merchant_category_mappings import MerchantCategoryMapping

MAPPINGS = [
    # 1. Alimentation, Supermarchés & Marques (Maakla w Tqadya) -> Courses
    {"keyword": "hanout", "category_name": "Courses"},
    {"keyword": "lhanout", "category_name": "Courses"},
    {"keyword": "7anout", "category_name": "Courses"},
    {"keyword": "moul lhanout", "category_name": "Courses"},
    {"keyword": "hwanet", "category_name": "Courses"},
    {"keyword": "epicerie", "category_name": "Courses"},
    {"keyword": "marjane", "category_name": "Courses"},
    {"keyword": "marjane market", "category_name": "Courses"},
    {"keyword": "carrefour", "category_name": "Courses"},
    {"keyword": "aswak", "category_name": "Courses"},
    {"keyword": "aswak assalam", "category_name": "Courses"},
    {"keyword": "bim", "category_name": "Courses"},
    {"keyword": "kazyon", "category_name": "Courses"},
    {"keyword": "supeco", "category_name": "Courses"},
    {"keyword": "atacadao", "category_name": "Courses"},
    {"keyword": "khdar", "category_name": "Courses"},
    {"keyword": "lkhedar", "category_name": "Courses"},
    {"keyword": "souq", "category_name": "Courses"},
    {"keyword": "sou9", "category_name": "Courses"},
    {"keyword": "marche", "category_name": "Courses"},
    {"keyword": "lmarche", "category_name": "Courses"},
    {"keyword": "gezzar", "category_name": "Courses"},
    {"keyword": "gzar", "category_name": "Courses"},
    {"keyword": "lhem", "category_name": "Courses"},
    {"keyword": "djaj", "category_name": "Courses"},
    {"keyword": "kefta", "category_name": "Courses"},
    {"keyword": "lkefta", "category_name": "Courses"},
    {"keyword": "hout", "category_name": "Courses"},
    {"keyword": "l7out", "category_name": "Courses"},
    {"keyword": "khobz", "category_name": "Courses"},
    {"keyword": "lkhobz", "category_name": "Courses"},
    {"keyword": "boulangerie", "category_name": "Courses"},
    {"keyword": "patisserie", "category_name": "Courses"},
    {"keyword": "amoud", "category_name": "Courses"},
    {"keyword": "paul", "category_name": "Courses"},
    {"keyword": "makla", "category_name": "Courses"},
    {"keyword": "lmakla", "category_name": "Courses"},
    {"keyword": "bouffe", "category_name": "Courses"},
    {"keyword": "ghda", "category_name": "Courses"},
    {"keyword": "lghda", "category_name": "Courses"},
    {"keyword": "3cha", "category_name": "Courses"},
    {"keyword": "le3cha", "category_name": "Courses"},
    {"keyword": "ftour", "category_name": "Courses"},
    {"keyword": "danone", "category_name": "Courses"},
    {"keyword": "hlib", "category_name": "Courses"},
    {"keyword": "7lib", "category_name": "Courses"},
    {"keyword": "zit", "category_name": "Courses"},
    {"keyword": "skar", "category_name": "Courses"},
    {"keyword": "atay", "category_name": "Courses"},
    {"keyword": "l9hwa", "category_name": "Courses"},
    {"keyword": "zari3a", "category_name": "Courses"},
    {"keyword": "zri3a", "category_name": "Courses"},
    {"keyword": "glid", "category_name": "Courses"},
    {"keyword": "lglid", "category_name": "Courses"},
    {"keyword": "biscuits", "category_name": "Courses"},
    {"keyword": "bimo", "category_name": "Courses"},

    # 2. Restauration rapide, Cafés & Sorties -> Restaurants
    {"keyword": "macdo", "category_name": "Restaurants"},
    {"keyword": "mcdo", "category_name": "Restaurants"},
    {"keyword": "mcdonalds", "category_name": "Restaurants"},
    {"keyword": "bk", "category_name": "Restaurants"},
    {"keyword": "burger king", "category_name": "Restaurants"},
    {"keyword": "kfc", "category_name": "Restaurants"},
    {"keyword": "tacos", "category_name": "Restaurants"},
    {"keyword": "chawarma", "category_name": "Restaurants"},
    {"keyword": "pizza", "category_name": "Restaurants"},
    {"keyword": "pizzeria", "category_name": "Restaurants"},
    {"keyword": "dominos", "category_name": "Restaurants"},
    {"keyword": "pizza hut", "category_name": "Restaurants"},
    {"keyword": "sushi", "category_name": "Restaurants"},
    {"keyword": "wok", "category_name": "Restaurants"},
    {"keyword": "asian", "category_name": "Restaurants"},
    {"keyword": "resto", "category_name": "Restaurants"},
    {"keyword": "restaurant", "category_name": "Restaurants"},
    {"keyword": "snak", "category_name": "Restaurants"},
    {"keyword": "snack", "category_name": "Restaurants"},
    {"keyword": "m7laba", "category_name": "Restaurants"},
    {"keyword": "mahlaba", "category_name": "Restaurants"},
    {"keyword": "panini", "category_name": "Restaurants"},
    {"keyword": "bocadillo", "category_name": "Restaurants"},
    {"keyword": "qahwa", "category_name": "Restaurants"},
    {"keyword": "qhiwa", "category_name": "Restaurants"},
    {"keyword": "cafe", "category_name": "Restaurants"},
    {"keyword": "café", "category_name": "Restaurants"},
    {"keyword": "starbucks", "category_name": "Restaurants"},
    {"keyword": "venezia", "category_name": "Restaurants"},
    {"keyword": "costa", "category_name": "Restaurants"},
    {"keyword": "glovo", "category_name": "Restaurants"},
    {"keyword": "glovos", "category_name": "Restaurants"},
    {"keyword": "deliveroo", "category_name": "Restaurants"},
    {"keyword": "jumia food", "category_name": "Restaurants"},
    {"keyword": "livraison", "category_name": "Restaurants"},

    # 3. Transport, Véhicules & Marques -> Taxi / VTC, Transport public, Voyage, Carburant, Transport, Parking, Entretien véhicule, Assurance auto
    {"keyword": "taxi", "category_name": "Taxi / VTC"},
    {"keyword": "petit taxi", "category_name": "Taxi / VTC"},
    {"keyword": "grand taxi", "category_name": "Taxi / VTC"},
    {"keyword": "koutchi", "category_name": "Taxi / VTC"},
    {"keyword": "indrive", "category_name": "Taxi / VTC"},
    {"keyword": "careem", "category_name": "Taxi / VTC"},
    {"keyword": "heetch", "category_name": "Taxi / VTC"},
    {"keyword": "uber", "category_name": "Taxi / VTC"},
    {"keyword": "yango", "category_name": "Taxi / VTC"},
    {"keyword": "vtc", "category_name": "Taxi / VTC"},
    {"keyword": "tobis", "category_name": "Transport public"},
    {"keyword": "toubis", "category_name": "Transport public"},
    {"keyword": "bus", "category_name": "Transport public"},
    {"keyword": "alsa", "category_name": "Transport public"},
    {"keyword": "tram", "category_name": "Transport public"},
    {"keyword": "tramway", "category_name": "Transport public"},
    {"keyword": "casa tramway", "category_name": "Transport public"},
    {"keyword": "train", "category_name": "Voyage"},
    {"keyword": "oncf", "category_name": "Voyage"},
    {"keyword": "alboraq", "category_name": "Voyage"},
    {"keyword": "buraq", "category_name": "Voyage"},
    {"keyword": "ctm", "category_name": "Voyage"},
    {"keyword": "sat", "category_name": "Voyage"},
    {"keyword": "ghazala", "category_name": "Voyage"},
    {"keyword": "markoub", "category_name": "Voyage"},
    {"keyword": "mazot", "category_name": "Carburant"},
    {"keyword": "lmazot", "category_name": "Carburant"},
    {"keyword": "essence", "category_name": "Carburant"},
    {"keyword": "sans plomb", "category_name": "Carburant"},
    {"keyword": "plein", "category_name": "Carburant"},
    {"keyword": "carburant", "category_name": "Carburant"},
    {"keyword": "afriquia", "category_name": "Carburant"},
    {"keyword": "winxo", "category_name": "Carburant"},
    {"keyword": "shell", "category_name": "Carburant"},
    {"keyword": "total", "category_name": "Carburant"},
    {"keyword": "petrom", "category_name": "Carburant"},
    {"keyword": "ola", "category_name": "Carburant"},
    {"keyword": "autoroute", "category_name": "Transport"},
    {"keyword": "peage", "category_name": "Transport"},
    {"keyword": "adm", "category_name": "Transport"},
    {"keyword": "jawaz", "category_name": "Transport"},
    {"keyword": "tri9", "category_name": "Transport"},
    {"keyword": "parking", "category_name": "Parking"},
    {"keyword": "blassa", "category_name": "Parking"},
    {"keyword": "3essas", "category_name": "Parking"},
    {"keyword": "gardien", "category_name": "Parking"},
    {"keyword": "lparking", "category_name": "Parking"},
    {"keyword": "lavage", "category_name": "Entretien véhicule"},
    {"keyword": "vidange", "category_name": "Entretien véhicule"},
    {"keyword": "mecanicien", "category_name": "Entretien véhicule"},
    {"keyword": "mikanik", "category_name": "Entretien véhicule"},
    {"keyword": "tola", "category_name": "Entretien véhicule"},
    {"keyword": "pneu", "category_name": "Entretien véhicule"},
    {"keyword": "pnowat", "category_name": "Entretien véhicule"},
    {"keyword": "assurance auto", "category_name": "Assurance auto"},
    {"keyword": "vignette", "category_name": "Assurance auto"},
    {"keyword": "lavisite", "category_name": "Entretien véhicule"},
    {"keyword": "la visite", "category_name": "Entretien véhicule"},

    # 4. Logement, Factures & Télécom -> Loyer / Charges logement / Factures / Téléphone / Internet / Entretien maison / Produits maison / Gaz
    {"keyword": "kera", "category_name": "Loyer"},
    {"keyword": "kra", "category_name": "Loyer"},
    {"keyword": "lkra", "category_name": "Loyer"},
    {"keyword": "loyer", "category_name": "Loyer"},
    {"keyword": "kraya", "category_name": "Loyer"},
    {"keyword": "syndic", "category_name": "Charges logement"},
    {"keyword": "sandaq", "category_name": "Charges logement"},
    {"keyword": "concierge", "category_name": "Charges logement"},
    {"keyword": "ma", "category_name": "Factures"},
    {"keyword": "lma", "category_name": "Factures"},
    {"keyword": "lydec", "category_name": "Factures"},
    {"keyword": "radeema", "category_name": "Factures"},
    {"keyword": "redal", "category_name": "Factures"},
    {"keyword": "amandis", "category_name": "Factures"},
    {"keyword": "radem", "category_name": "Factures"},
    {"keyword": "do", "category_name": "Factures"},
    {"keyword": "dow", "category_name": "Factures"},
    {"keyword": "ddow", "category_name": "Factures"},
    {"keyword": "kahraba", "category_name": "Factures"},
    {"keyword": "électricité", "category_name": "Factures"},
    {"keyword": "iam", "category_name": "Téléphone"},
    {"keyword": "maroc telecom", "category_name": "Téléphone"},
    {"keyword": "inwi", "category_name": "Téléphone"},
    {"keyword": "orange", "category_name": "Téléphone"},
    {"keyword": "recharge", "category_name": "Téléphone"},
    {"keyword": "ta3bia", "category_name": "Téléphone"},
    {"keyword": "solde", "category_name": "Téléphone"},
    {"keyword": "forfait", "category_name": "Téléphone"},
    {"keyword": "carte", "category_name": "Téléphone"},
    {"keyword": "wifi", "category_name": "Internet"},
    {"keyword": "internet", "category_name": "Internet"},
    {"keyword": "adsl", "category_name": "Internet"},
    {"keyword": "fibre", "category_name": "Internet"},
    {"keyword": "connexion", "category_name": "Internet"},
    {"keyword": "facture", "category_name": "Factures"},
    {"keyword": "lfactura", "category_name": "Factures"},
    {"keyword": "warka", "category_name": "Factures"},
    {"keyword": "lwarqa", "category_name": "Factures"},
    {"keyword": "tasbi9", "category_name": "Factures"},
    {"keyword": "drougri", "category_name": "Entretien maison"},
    {"keyword": "droguerie", "category_name": "Entretien maison"},
    {"keyword": "bricolage", "category_name": "Entretien maison"},
    {"keyword": "plombier", "category_name": "Entretien maison"},
    {"keyword": "trician", "category_name": "Entretien maison"},
    {"keyword": "javel", "category_name": "Produits maison"},
    {"keyword": "tid", "category_name": "Produits maison"},
    {"keyword": "sanicroix", "category_name": "Produits maison"},
    {"keyword": "ndafa", "category_name": "Produits maison"},
    {"keyword": "ménage", "category_name": "Entretien maison"},
    {"keyword": "femme de menage", "category_name": "Entretien maison"},
    {"keyword": "bota", "category_name": "Gaz"},
    {"keyword": "lbota", "category_name": "Gaz"},
    {"keyword": "gaz", "category_name": "Gaz"},
    {"keyword": "ghaz", "category_name": "Gaz"},

    # 5. Santé, Beauté & Soins -> Consultation médicale / Pharmacie / Santé / Soins personnels
    {"keyword": "tbib", "category_name": "Consultation médicale"},
    {"keyword": "t'bib", "category_name": "Consultation médicale"},
    {"keyword": "medecin", "category_name": "Consultation médicale"},
    {"keyword": "docteur", "category_name": "Consultation médicale"},
    {"keyword": "fisita", "category_name": "Consultation médicale"},
    {"keyword": "visite", "category_name": "Consultation médicale"},
    {"keyword": "frmasyan", "category_name": "Pharmacie"},
    {"keyword": "pharmacie", "category_name": "Pharmacie"},
    {"keyword": "sighdaliya", "category_name": "Pharmacie"},
    {"keyword": "para", "category_name": "Pharmacie"},
    {"keyword": "parapharmacie", "category_name": "Pharmacie"},
    {"keyword": "dwa", "category_name": "Pharmacie"},
    {"keyword": "ddwa", "category_name": "Pharmacie"},
    {"keyword": "medicament", "category_name": "Pharmacie"},
    {"keyword": "vitamin", "category_name": "Pharmacie"},
    {"keyword": "vitamines", "category_name": "Pharmacie"},
    {"keyword": "sbitar", "category_name": "Santé"},
    {"keyword": "clinique", "category_name": "Santé"},
    {"keyword": "clinik", "category_name": "Santé"},
    {"keyword": "urgence", "category_name": "Santé"},
    {"keyword": "t7alil", "category_name": "Santé"},
    {"keyword": "labo", "category_name": "Santé"},
    {"keyword": "dentiste", "category_name": "Santé"},
    {"keyword": "coiffeur", "category_name": "Soins personnels"},
    {"keyword": "hallaq", "category_name": "Soins personnels"},
    {"keyword": "7allaq", "category_name": "Soins personnels"},
    {"keyword": "salon", "category_name": "Soins personnels"},
    {"keyword": "hsana", "category_name": "Soins personnels"},
    {"keyword": "coupe", "category_name": "Soins personnels"},
    {"keyword": "hammam", "category_name": "Soins personnels"},
    {"keyword": "lhammam", "category_name": "Soins personnels"},
    {"keyword": "massage", "category_name": "Soins personnels"},
    {"keyword": "spa", "category_name": "Soins personnels"},
    {"keyword": "manicure", "category_name": "Soins personnels"},
    {"keyword": "soin", "category_name": "Soins personnels"},
    {"keyword": "maquillage", "category_name": "Soins personnels"},
    {"keyword": "makeup", "category_name": "Soins personnels"},
    {"keyword": "flormar", "category_name": "Soins personnels"},
    {"keyword": "yves rocher", "category_name": "Soins personnels"},
    {"keyword": "mac", "category_name": "Soins personnels"},
    {"keyword": "kiko", "category_name": "Soins personnels"},

    # 6. Éducation & Enfants -> Frais scolaires enfants / Garde d'enfants / Aide famille
    {"keyword": "mdrassa", "category_name": "Frais scolaires enfants"},
    {"keyword": "ecole", "category_name": "Frais scolaires enfants"},
    {"keyword": "madrassa", "category_name": "Frais scolaires enfants"},
    {"keyword": "creche", "category_name": "Garde d'enfants"},
    {"keyword": "garderie", "category_name": "Garde d'enfants"},
    {"keyword": "lycee", "category_name": "Frais scolaires enfants"},
    {"keyword": "maktaba", "category_name": "Frais scolaires enfants"},
    {"keyword": "librairie", "category_name": "Frais scolaires enfants"},
    {"keyword": "koutoub", "category_name": "Frais scolaires enfants"},
    {"keyword": "dftar", "category_name": "Frais scolaires enfants"},
    {"keyword": "fournitures", "category_name": "Frais scolaires enfants"},
    {"keyword": "swaye3", "category_name": "Frais scolaires enfants"},
    {"keyword": "centre", "category_name": "Frais scolaires enfants"},
    {"keyword": "language", "category_name": "Frais scolaires enfants"},
    {"keyword": "cours", "category_name": "Frais scolaires enfants"},
    {"keyword": "soutien", "category_name": "Frais scolaires enfants"},
    {"keyword": "drari", "category_name": "Aide famille"},
    {"keyword": "wlad", "category_name": "Aide famille"},
    {"keyword": "enfants", "category_name": "Aide famille"},
    {"keyword": "couches", "category_name": "Aide famille"},
    {"keyword": "hlib drari", "category_name": "Aide famille"},

    # 7. Loisirs, Numérique & Lifestyle -> Loisirs / Voyage / Abonnements
    {"keyword": "tsserkila", "category_name": "Loisirs"},
    {"keyword": "tserkila", "category_name": "Loisirs"},
    {"keyword": "khorja", "category_name": "Loisirs"},
    {"keyword": "khrija", "category_name": "Loisirs"},
    {"keyword": "dawra", "category_name": "Loisirs"},
    {"keyword": "s7abi", "category_name": "Loisirs"},
    {"keyword": "shabi", "category_name": "Loisirs"},
    {"keyword": "amis", "category_name": "Loisirs"},
    {"keyword": "shab", "category_name": "Loisirs"},
    {"keyword": "l3echran", "category_name": "Loisirs"},
    {"keyword": "kora", "category_name": "Loisirs"},
    {"keyword": "match", "category_name": "Loisirs"},
    {"keyword": "foot", "category_name": "Loisirs"},
    {"keyword": "terrain", "category_name": "Loisirs"},
    {"keyword": "tirane", "category_name": "Loisirs"},
    {"keyword": "salle", "category_name": "Loisirs"},
    {"keyword": "la salle", "category_name": "Loisirs"},
    {"keyword": "gym", "category_name": "Loisirs"},
    {"keyword": "sport", "category_name": "Loisirs"},
    {"keyword": "city club", "category_name": "Loisirs"},
    {"keyword": "fitness", "category_name": "Loisirs"},
    {"keyword": "cinema", "category_name": "Loisirs"},
    {"keyword": "film", "category_name": "Loisirs"},
    {"keyword": "megarama", "category_name": "Loisirs"},
    {"keyword": "imax", "category_name": "Loisirs"},
    {"keyword": "theatre", "category_name": "Loisirs"},
    {"keyword": "activite", "category_name": "Loisirs"},
    {"keyword": "activites", "category_name": "Loisirs"},
    {"keyword": "activity", "category_name": "Loisirs"},
    {"keyword": "activities", "category_name": "Loisirs"},
    {"keyword": "voyage", "category_name": "Voyage"},
    {"keyword": "msafer", "category_name": "Voyage"},
    {"keyword": "safar", "category_name": "Voyage"},
    {"keyword": "weekend", "category_name": "Voyage"},
    {"keyword": "wknd", "category_name": "Voyage"},
    {"keyword": "hotel", "category_name": "Voyage"},
    {"keyword": "airbnb", "category_name": "Voyage"},
    {"keyword": "netflix", "category_name": "Abonnements"},
    {"keyword": "spotify", "category_name": "Abonnements"},
    {"keyword": "iptv", "category_name": "Abonnements"},
    {"keyword": "psn", "category_name": "Abonnements"},
    {"keyword": "xbox", "category_name": "Abonnements"},
    {"keyword": "steam", "category_name": "Abonnements"},
    {"keyword": "anghami", "category_name": "Abonnements"},

    # 8. Shopping, Vêtements & E-commerce -> Shopping / Cadeaux & dons
    {"keyword": "hwayej", "category_name": "Shopping"},
    {"keyword": "lhwayej", "category_name": "Shopping"},
    {"keyword": "vetements", "category_name": "Shopping"},
    {"keyword": "ksiywa", "category_name": "Shopping"},
    {"keyword": "tricot", "category_name": "Shopping"},
    {"keyword": "serwal", "category_name": "Shopping"},
    {"keyword": "sbat", "category_name": "Shopping"},
    {"keyword": "sbbat", "category_name": "Shopping"},
    {"keyword": "chaussure", "category_name": "Shopping"},
    {"keyword": "sebbat", "category_name": "Shopping"},
    {"keyword": "espadrille", "category_name": "Shopping"},
    {"keyword": "mall", "category_name": "Shopping"},
    {"keyword": "morocco mall", "category_name": "Shopping"},
    {"keyword": "socco", "category_name": "Shopping"},
    {"keyword": "marina", "category_name": "Shopping"},
    {"keyword": "boutique", "category_name": "Shopping"},
    {"keyword": "zara", "category_name": "Shopping"},
    {"keyword": "lc waikiki", "category_name": "Shopping"},
    {"keyword": "defacto", "category_name": "Shopping"},
    {"keyword": "marwa", "category_name": "Shopping"},
    {"keyword": "decathlon", "category_name": "Shopping"},
    {"keyword": "kiabi", "category_name": "Shopping"},
    {"keyword": "shein", "category_name": "Shopping"},
    {"keyword": "aliexpress", "category_name": "Shopping"},
    {"keyword": "jumia", "category_name": "Shopping"},
    {"keyword": "amazon", "category_name": "Shopping"},
    {"keyword": "cadeau", "category_name": "Cadeaux & dons"},
    {"keyword": "kado", "category_name": "Cadeaux & dons"},
    {"keyword": "anniversaire", "category_name": "Cadeaux & dons"},
    {"keyword": "3id milad", "category_name": "Cadeaux & dons"},

    # 9. Banque, Dettes & Obligations -> Paiement dette / Frais administratifs / Aide famille / Cadeaux & dons / Divers
    {"keyword": "crédit", "category_name": "Paiement dette"},
    {"keyword": "traita", "category_name": "Paiement dette"},
    {"keyword": "traite", "category_name": "Paiement dette"},
    {"keyword": "banka", "category_name": "Frais administratifs"},
    {"keyword": "agios", "category_name": "Frais administratifs"},
    {"keyword": "frais", "category_name": "Frais administratifs"},
    {"keyword": "cih", "category_name": "Frais administratifs"},
    {"keyword": "bmce", "category_name": "Frais administratifs"},
    {"keyword": "bcp", "category_name": "Frais administratifs"},
    {"keyword": "chaabi", "category_name": "Frais administratifs"},
    {"keyword": "bmci", "category_name": "Frais administratifs"},
    {"keyword": "attijari", "category_name": "Frais administratifs"},
    {"keyword": "salaf", "category_name": "Paiement dette"},
    {"keyword": "din", "category_name": "Paiement dette"},
    {"keyword": "rid", "category_name": "Paiement dette"},
    {"keyword": "rejje3", "category_name": "Paiement dette"},
    {"keyword": "kridi", "category_name": "Paiement dette"},
    {"keyword": "wafacash", "category_name": "Frais administratifs"},
    {"keyword": "cashplus", "category_name": "Frais administratifs"},
    {"keyword": "western union", "category_name": "Frais administratifs"},
    {"keyword": "virement", "category_name": "Divers"},
    {"keyword": "dar", "category_name": "Aide famille"},
    {"keyword": "ldar", "category_name": "Aide famille"},
    {"keyword": "lwalidin", "category_name": "Aide famille"},
    {"keyword": "walidin", "category_name": "Aide famille"},
    {"keyword": "mmi", "category_name": "Aide famille"},
    {"keyword": "bba", "category_name": "Aide famille"},
    {"keyword": "lwalid", "category_name": "Aide famille"},
    {"keyword": "zaka", "category_name": "Cadeaux & dons"},
    {"keyword": "sadaqa", "category_name": "Cadeaux & dons"},
    {"keyword": "sdaqa", "category_name": "Cadeaux & dons"},
    {"keyword": "jame3", "category_name": "Cadeaux & dons"},
    {"keyword": "masjid", "category_name": "Cadeaux & dons"},
    {"keyword": "3chor", "category_name": "Cadeaux & dons"},
    {"keyword": "flous", "category_name": "Divers"},
    {"keyword": "srf", "category_name": "Divers"},
    {"keyword": "sarf", "category_name": "Divers"},
    {"keyword": "jibi", "category_name": "Divers"},
    {"keyword": "kherja", "category_name": "Divers"},
    {"keyword": "retrait", "category_name": "Divers"},
]


async def seed_moroccan_nlp_mappings() -> None:
    SessionLocal = get_sessionmaker()
    async with SessionLocal() as session:
        added_count = 0
        skipped_count = 0

        for item in MAPPINGS:
            # Query if keyword mapping already exists to prevent duplicate key errors
            result = await session.execute(
                select(MerchantCategoryMapping).where(
                    MerchantCategoryMapping.keyword == item["keyword"]
                )
            )
            existing = result.scalar_one_or_none()

            if not existing:
                new_mapping = MerchantCategoryMapping(
                    keyword=item["keyword"],
                    category_name=item["category_name"]
                )
                session.add(new_mapping)
                added_count += 1
            else:
                # Optionally update existing mapping if the category changed
                if existing.category_name != item["category_name"]:
                    existing.category_name = item["category_name"]
                    added_count += 1
                else:
                    skipped_count += 1

        await session.commit()
        print(f"✅ Seeding completed: Added/Updated {added_count} keywords, skipped {skipped_count} identical keywords.")


if __name__ == "__main__":
    asyncio.run(seed_moroccan_nlp_mappings())
